### ISSUE TITLE
Staggered brine elemental entrance

### ISSUE THREAD

**Issue by freiburgermsu** [freiburgermsu/ROSSpy#3]
Stagger the plotting of elements may be preferable to [the present method ](https://github.com/freiburgermsu/ROSSpy/blob/main/rosspy/ro.py#L981-L986) of waiting until all elements exhibit a concentration >1E-16 molal. This will capture edge systems where a few ions only surpass this threshold near the end of the module.

**Comment by Lixuanan** [comment]
Dear Prof. freiburgermsu,

I find that the sentense 'ross.execute()' can not work. Do you know what's the problem?

Lixuan

**Comment by freiburgermsu** [comment]
Hello @Lixuanan ,

There are numerous possible causes of the error. Can you please paste the TraceBack error message that you observe in this thread?

**Comment by freiburgermsu** [comment]
@Lixuanan I just upgraded the module version via `pip install --upgrade rosspy` in my terminal and successfully executed the following sequence:
```python
from rosspy import ROSSPkg
ross = ROSSPkg('pitzer', 'scaling')
ross.reactive_transport(200, 'all_distance')
ross.feed_geochemistry('red_sea')
ross.execute()
```
Perhaps you must upgrade your version of `ROSSpy`? What version do you see when you execute `pip show rosspy` in your terminal?

**Comment by Lixuanan** [comment]
Dear Prof. Freiburgermsu,

Thank you very much for your prompt response. We are running this file 'ROSSpy-main\examples\scaling\scale_validation\Karabelas_et_al-2014\Karabelas_et_al-2014.ipynb'. However, it  went wrong when came the the command ross.execute(), as shown below. My ROSSpy version is 0.1.1 as shown in the second picture below. I will upgrage the ROSSpy as you recommended in the other email anyway.

Best regards,
Lixuan


[cid:96558760-94c8-4d8e-b972-3ef65daea474]





[cid:ad0bb91c-0e48-441e-8ce3-1a553f7d0cff]

[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月17日 21:34
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Hello @Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7Cd0b0bdce911d4b7fe0fe08da383c327d%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637884128435279686%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6W6lpuszqo%2FivHx4dWikBPT2Ya26U0F5o8PeE1aPhcc%3D&reserved=0> ,

There are numerous possible causes of the error. Can you please paste the TraceBack error message that you observe in this thread?

―

**Comment by freiburgermsu** [comment]
Hello @Lixuanan ,

Your pictures unfortunately did not render. Can you please send them again? 

I just successfully executed that Notebook. I will have a better understanding of the problem from the pictures. Are you executing the Notebooks through Anaconda?

**Comment by freiburgermsu** [comment]
Maybe try `git pull origin main` in the `ROSS` repository to update the Notebook as well?

**Comment by Lixuanan** [comment]
Yes I through Anaconda to run this code. I am sorry the pictures didn't render successfully, I send it again.

[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月17日 22:11
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Hello @Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7C570dce24154a4081533808da38415d4f%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637884150636194054%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tiCOFXnp6N6BX7znNTS2QFEwuf7XxgM9zQtoacQ0vNg%3D&reserved=0> ,

Your pictures unfortunately did not render. Can you please send them?

I just successfully executed that Notebook. I will have a better understanding of the problem from the pictures. Are you executing the Notebooks through Anaconda?

―

**Comment by Lixuanan** [comment]
Thank you so much! I will try this. Tomorrow I will also talk with my colleague about my errors.


[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月17日 22:12
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Maybe try git pull origin main in the ROSS repository to update the content as well?

―

**Comment by freiburgermsu** [comment]
I will await your word tomorrow, or pictures of the errors. I can also meet over zoom to troubleshoot the errors.

Thank you :)

**Comment by Lixuanan** [comment]
Dear  Freiburgermsu,

Good morning!
I am sorry to bother you. Do you have time today? Can we have a short chat online through zoom?

Best regards,
Lixuan

[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月17日 23:13
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


I will await the your word tomorrow, or pictures of the errors. I can also meet over zoom to troubleshoot the errors.

Thank you :)

―

**Comment by freiburgermsu** [comment]
Good morning @Lixuanan ,

I created a zoom meeting for us. Are you available at 10:00 EST? 


Topic: ROSSpy troubleshoot
Time: May 18, 2022 10:00 AM Eastern Time (US and Canada)

Join Zoom Meeting
https://uvic.zoom.us/j/89904963045?pwd=L0VOQUJjVndvd2ZoWWZPNi9ReVZWdz09

Meeting ID: 899 0496 3045
Password: 878788

**Comment by Lixuanan** [comment]
Thank you!  I and my colleague will join it in time.

Lixuan An and Min Yang

[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月18日 14:37
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Good morning @Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7Cbfbda5d93e094cd5f62008da38cb1deb%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637884742275766366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eiGmHCFsl%2FiuG2E8nQHvxe1vk5VWdnLyI4ot2pyZ33U%3D&reserved=0> ,

I created a zoom meeting for us. Are you available at 10:00 EST?

Topic: ROSSpy troubleshoot
Time: May 18, 2022 10:00 AM Eastern Time (US and Canada)

Join Zoom Meeting
https://uvic.zoom.us/j/89904963045?pwd=L0VOQUJjVndvd2ZoWWZPNi9ReVZWdz09<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuvic.zoom.us%2Fj%2F89904963045%3Fpwd%3DL0VOQUJjVndvd2ZoWWZPNi9ReVZWdz09&data=05%7C01%7CLixuan.An%40ugent.be%7Cbfbda5d93e094cd5f62008da38cb1deb%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637884742275766366%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NfrBB7AMicCRm7TVdPxLt8aI1PtitFbMupaea37gYp4%3D&reserved=0>

Meeting ID: 899 0496 3045
Password: 878788

―

**Comment by freiburgermsu** [comment]
Hello @Lixuanan !

I was able to resolve the error with Min Yang. Thank you all for detailing the bug. Freely share any other bugs or ideas by creating new issues on this page.

Thank you :)
    Andrew

**Comment by Lixuanan** [comment]
Hello Andrew,

Good Morning!

I am so appreciate that you can help us solve the bugs. Thank you so much!

I am a Phd student in UGent University. My research topic is about Group Anomaly Detection based on Extreme Value Theory and One-class Support Measure Machines.
If you interested in it, hope we can keep in touch more in the future.

The website of our group is as followed:
https://kermit.ugent.be/

Best regards,
Lixuan An

[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月18日 22:26
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Hello @Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7C92396357ad7d450a3e7508da390cb88a%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637885024049244198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZKXfv8wM49%2B7ymP472FVZQSv%2FbuhHh%2BDWHClDaje%2FHw%3D&reserved=0> !

I was able to resolve the error with Min Yang. Thank you all for detailing the bug. Freely share any other bugs or ideas by creating new issues on this page.

Thank you :)
Andrew

―

**Comment by freiburgermsu** [comment]
Dear @Lixuanan ,

Thank you for communicating the error via this Issues page! I am pleased to have helped, and to have connected with you all. 

Your research group seems diverse and interesting! I will keep it in mind. Connect with me on LinkedIn or follow my GitHub account to remain in-touch.

Thank you :) 
    Andrew

**Comment by Lixuanan** [comment]
Dear Freiburgermsu,

Thank you for your quick response. I upgrated the package and executed the sequence you sent, but no lucky. I think it was the command ross.execute() stuck me again.

Best regards,
Lixuan



[1630728437638]
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年5月17日 21:51
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [ /ROSSpy] Staggered brine elemental entrance (Issue #3)


@Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7C0ec9cc5a1ce249128e7008da383e9d7f%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C637884138820164282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gDdulg8LAowfV6IVsUH0PZ0fxhjiT%2BGYG5lvwbuPQ4w%3D&reserved=0> I just upgraded the module version via pip install --upgrade rosspy in my terminal and successfully executed the following sequence:

from rosspy import ROSSPkg
ross = ROSSPkg('pitzer', 'scaling')
ross.reactive_transport(200, 'all_distance')
ross.feed_geochemistry('red_sea')
ross.execute()

Perhaps you must upgrade your version of ROSSpy? What version do you see when you execute pip show rosspy in your terminal?

―

**Comment by freiburgermsu** [comment]
Hello @Lixuanan !

Thank you for communicating your dilemma. I resolved Min Yang's issue by [installing PHREEQC ](https://water.usgs.gov/water-resources/software/PHREEQC/index.html) on his local machine, since ROSSpy is based upon this software. Do you have PHREEQC installed on your computer? Can you share the error message that you receive so that I can best understand your situation?

Andrew

**Comment by Lixuanan** [comment]
Hi Andrew,

I am really really sorry. It's my fault I just found this email when I was sorting out my spam mails today.

About the ROSSpy, Min Yang initially found the error message and ask me for help, and then I and Nusret had same errors with him. So we tried to contact you. After some online meetings with you, he solved it. I and Nusret we didn't install the PHREEQC, I think it will also work on our PC. If you want I can install it tomorrow, I hope it's not late.

I apologize again.
Best regards,
Lixuan

[cid:2a24e6cf-55eb-482c-aa01-54bce83d9f6f]<https://www.ugent.be/bw>
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


***@***.***?anonymous&ep=signature>         ***@***.***?anonymous&ep=signature>
________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年11月5日 05:01
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Hello @Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7C7852944d1df24579572208dabee26e4a%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638032176970005396%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i3evVJm6rmjkKLtLsGDaNJ6ee9capo7%2FhHVsRVtsamw%3D&reserved=0> !

Thank you for communicating your dilemma. I resolved Min Yang's issue by installing PHREEQC <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwater.usgs.gov%2Fwater-resources%2Fsoftware%2FPHREEQC%2Findex.html&data=05%7C01%7CLixuan.An%40ugent.be%7C7852944d1df24579572208dabee26e4a%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638032176970161632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HOWDnGSoJk0tqLqG9mNrq9bYg0qnAoRZPmlXZxQJ%2Bo8%3D&reserved=0> on his local machine, since ROSSpy is based upon this software. Do you have PHREEQC installed on your computer? Can you share the error message that you receive so that I can best understand your situation?

Andrew

―

**Comment by freiburgermsu** [comment]
Hello @Lixuanan!

Thank you for clarifying the situation. I would appreciate if you installed ROSSpy and let me know if it works for you. We are planning to publish our work soon, and we would benefit from your third-party confirmation that it works as is intended.

Thank you so much :)

      Andrew

**Comment by Lixuanan** [comment]
Hi Andrew,

If you receive my email, can you tell me? I'm afraid it went into spam.

Thanks for your reply. I am happy to do that😀. Today I run the code of this link: https://github.com/freiburgermsu/ROSSpy the 'examples/scaling/scaling_validation' directory on both my PC and Linux.

In my own PC, it works. Firstly I run 'pip install rosspy', and then download Windows version PHREEQC<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwater.usgs.gov%2Fwater-resources%2Fsoftware%2FPHREEQC%2Findex.html&data=05%7C01%7CLixuan.An%40ugent.be%7C7852944d1df24579572208dabee26e4a%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638032176970161632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HOWDnGSoJk0tqLqG9mNrq9bYg0qnAoRZPmlXZxQJ%2Bo8%3D&reserved=0> from https://water.usgs.gov/water-resources/software/PHREEQC/index.html. After that the example of the ROSSpy simulation successfully works, I obtain the result and the plot.
[cid:9325afe1-9d24-4be5-a5a6-543c90738ae9]
[cid:5a8ec290-4680-4a5d-8402-4eedaa4b598b]

However, it failed on Linux. When I run the same code on Google colab, I met the problem of installing PHREEQC<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwater.usgs.gov%2Fwater-resources%2Fsoftware%2FPHREEQC%2Findex.html&data=05%7C01%7CLixuan.An%40ugent.be%7C7852944d1df24579572208dabee26e4a%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638032176970161632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HOWDnGSoJk0tqLqG9mNrq9bYg0qnAoRZPmlXZxQJ%2Bo8%3D&reserved=0>. I share the link of google colab: https://colab.research.google.com/github/freiburgermsu/ROSSpy/blob/main/examples/scaling/scale_validation/Karabelas_et_al-2014/Karabelas_et_al-2014.ipynb You can see from the link it shows the error of the library `GLIBC_2.29'.
[cid:03e09904-0629-443d-b5ff-7e6b61eb4022]

I remember it is the same error the last time we tried to run it on linux (about the library `GLIBC_2.29'). But I can be very sure it works successfully on my PC.

Best regards,
Lixuan

[https://colab.research.google.com/img/colab_favicon_256px.png]<https://colab.research.google.com/github/freiburgermsu/ROSSpy/blob/main/examples/scaling/scale_validation/Karabelas_et_al-2014/Karabelas_et_al-2014.ipynb>
Google Colaboratory<https://colab.research.google.com/github/freiburgermsu/ROSSpy/blob/main/examples/scaling/scale_validation/Karabelas_et_al-2014/Karabelas_et_al-2014.ipynb>
colab.research.google.com


PHREEQC Version 3 Downloads - USGS<https://water.usgs.gov/water-resources/software/PHREEQC/index.html>
PHREEQC Version 3 Downloads. Return to main PHREEQC Version 3 Page. Graphical User Interfaces. Windows 32-bit. phreeqci-3.7.3-15968.msi [13M] - Executable, database files, examples, PDF documentation Notepad + + interface - Appelo's Notepad + + interface to PHREEQC version 3; Batch Versions of PHREEQC
water.usgs.gov



[cid:b3574d5a-d31a-4f34-baa8-c5c14e959857]<https://www.ugent.be/bw>
Lixuan An
Doctoral researcher
T +32 467667984

Department Data Analysis and Mathematical Modelling

Campus Coupure, Location, Coupure links 653, B-9000 Ghent, Belgium ***@***.***,3.7067699,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x47c3716be33c0fdb:0x13de981a81d5c757!2m2!1d3.7089586!2d51.0527795!3e0?hl=nl>
T administration office +32 9 264 59 32

www.ugent.be<https://www.ugent.be/bw/en>

e-maildisclaimer<https://helpdesk.ugent.be/e-maildisclaimer.php>


***@***.***?anonymous&ep=signature>         ***@***.***?anonymous&ep=signature>
________________________________
发件人: freiburgermsu ***@***.***>
发送时间: 2022年11月23日 07:19
收件人: freiburgermsu/ROSSpy ***@***.***>
抄送: Lixuan An ***@***.***>; Mention ***@***.***>
主题: Re: [freiburgermsu/ROSSpy] Staggered brine elemental entrance (Issue #3)


Hello @Lixuanan<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLixuanan&data=05%7C01%7CLixuan.An%40ugent.be%7C728a8be48fae4a8301a808dacd1aa238%7Cd7811cdeecef496c8f91a1786241b99c%7C1%7C0%7C638047811538921965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HI6ANCK%2Bc2kWsdrQuhp9gI7M8ECSQ9Lv3FcpTmrOnxY%3D&reserved=0>!

Thank you for clarifying the situation. I would appreciate if you installed ROSSpy and let me know if it works for you. We are planning to publish our work soon, and we would benefit from your third-party confirmation that it works as is intended.

Thank you so much :)

  Andrew

**Comment by freiburgermsu** [comment]
Hello Lixuan!

Thank you for verifying the ROSSpy executes on your Windows PC! I believe that the Linux error is from an incompatible import with the 18.* version of Ubuntu on Google Collab. Nusret suggested constructing a docker image of ROSSpy that can be executed in Google Collab’s version of Ubuntu; I will investigate this option and communicate when it is developed next year.

Thank you and enjoy the Holiday season :)
    Andrew
